# 此ssh key的内容需要手动执行 ssh-keygen -t rsa -b 2048 -f ./id_rsa -N "" -q
# 如果复用已有的ssh key, 将公钥和私钥复制放进去即可
apiVersion: v1
kind: Secret
metadata:
  name: ssh-keys-secret
  namespace: vmcontrolhub
# 标准 SSH 密钥类型
type: kubernetes.io/ssh-auth
stringData:
  # 粘贴自己的 id_rsa 私钥全文，保留格式
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ....................................
    -----END OPENSSH PRIVATE KEY-----

  # 粘贴自己的 id_rsa.pub 公钥全文，保留格式
  ssh-publickey: |
    ssh-rsa ....................................

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-secret
  namespace: vmcontrolhub
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root-mysql-vmcontrolhub"

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-app-secret
  namespace: vmcontrolhub
type: Opaque
stringData:
  # 直接写明文，Kubernetes会自动转成Base64
  MYSQL_USER: "vmcontrolhub"
  MYSQL_PASSWORD: "vmcontrolhub"
  MYSQL_DATABASE: "vmcontrolhub"

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: vmcontrolhub
type: Opaque
stringData:
  REDIS_PASSWORD: "vmcontrolhub-redis"


---
apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  namespace: vmcontrolhub
type: Opaque
stringData:
  SECRET_KEY: "da266a3ffc9da06043dff80df46e3a59b3179a6b9f0b7d8b3994e15917764cf2d5b81523dbf30ec1d3a3cbfec459197a11814a796351158b38edee92496de7c"
